spring:
  application:
    name: why-n-coming
  datasource:
    url: jdbc:postgresql://localhost:5432/whyncoming
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update        # ??? validate, ?? ?? update? ??
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    time-zone: Asia/Seoul

springdoc:
  api-docs:
    path: /api-docs         # ?? /v3/api-docs ? /api-docs ? ??
  swagger-ui:
    path: /docs             # ?? /swagger-ui.html ? /docs ? ??
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace   # ??? ?????? ?? ?? ?
