spring:
  application:
    name: why-n-coming

  # 공통 JPA/Flyway/시간대
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate     # 스키마는 Flyway가 관리, 운영 습관: validate 고정
    properties:
      hibernate:
        format_sql: true
        # dialect는 Spring Boot가 드라이버로 자동 감지하므로 생략 가능(명시해도 무방)
        # dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    # 기존 운영 DB에 테이블이 이미 있을 때만 true. 신규 DB면 false 권장
    baseline-on-migrate: false
  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 비밀/외부설정 분리 (파일이 없어도 앱이 뜨도록 optional)
  config:
    import:
      - optional:classpath:application-secret.yml
      - optional:classpath:application-local.yml
      - optional:classpath:application-toss.yml
      - optional:classpath:application-jwt.yml
      - optional:classpath:application-ai.yml

# 보안 관련(BCrypt)
security:
  bcrypt:
    cost: 10

# OpenAPI(Swagger)
springdoc:
  api-docs:
    path: /api-docs        # 기본은 /v3/api-docs, 커스텀 사용 시 여기로 노출
  swagger-ui:
    path: /                 # 기본은 /swagger-ui/index.html, 여기로 접속 가능
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

# 공통 로깅(상세 SQL 로깅은 프로파일에서 분리)
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false