spring:
  application:
    name: why-n-coming
  datasource:
    url: jdbc:postgresql://localhost:5432/whyncoming
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update        # ← 중요: 스키마는 Flyway가 만들고, JPA는 검증만 #update는 jpa 가 스키마 생성/수정까지 함   # 운영에서는 ddl-auto: validate, 로컬 임시 개발이라도 update는 습관 들이지 않는 걸 추천해요. (실수로 운영에 반영될 위험)
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    time-zone: Asia/Seoul
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true   # 기존 DB에 테이블이 이미 있을 때 첫 실행 시 베이스라인 처리
security:
 bcrypt:
  cost: 12

springdoc:
  api-docs:
    path: /api-docs         # ?? /v3/api-docs ? /api-docs ? ??
  swagger-ui:
    path: /docs             # ?? /swagger-ui.html ? /docs ? ??
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace   # ??? ?????? ?? ?? ?
